name: CookingPlugin
version: 1.0
main: com.example.cookingplugin.CookingPlugin
author: eogd
api-version: 1.12
description: A cooking plugin for Spigot 1.12.2
commands:
  cook:
    description: Creates a new cooking recipe.
    usage: /<command> <name> <hunger> <saturation> [effect] [level] [duration]
  cooklang:
    description: Switches the language for recipe ingredients.
    usage: /<command> <cn|en>